# -*- coding: utf-8 -*-
"""NumPy Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Y8gf0NqfXxDukh77wqkhFwqRpoeDNPw
"""

import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

a = np.array([1, 2, 3, 4, 5, 6])
a

a[0]

a[0] = 10
a

a[:3]

b = a[3:]
b

b[0] = 40
a

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

a[1, 3]

a.ndim

a.shape
len(a.shape) == a.ndim

a.size
import math
a.size == math.prod(a.shape)

a.dtype

a.size
import math
a.size == math.prod(a.shape)

a.dtype

np.zeros(2)

np.ones(2)

# Create an empty array with 2 elements
np.empty(2)

np.arange(4)

np.linspace(0, 10, num=5)

np.arange(2, 9, 2)

x = np.ones(2, dtype=np.int64)
x