# -*- coding: utf-8 -*-
"""Numpy Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-bBnUJQOg-LvtjFMZ1cLrh_kp5w32JU
"""

import numpy as np

# Create a sample dataset: Student Performance Data
# Columns: Student_ID, Math_Score, Science_Score, English_Score, Hours_Studied,Attendance_Percentagenp
np.random.seed(42)
data = np.array([
[1, 85, 78, 92, 5.5, 95],
[2, 92, 88, 85, 7.0, 98],
[3, 78, 82, 88, 4.0, 90],
[4, 95, 91, 94, 8.0, 99],
[5, 67, 72, 75, 3.0, 85],
[6, 88, 85, 90, 6.0, 96],
[7, 73, 68, 70, 3.5, 88],
[8, 91, 89, 87, 7.5, 97],
[9, 82, 80, 83, 5.0, 92],
[10, 76, 74, 79, 4.5, 89]
])

#print data
print(data)
# ============ BASIC ARRAY OPERATIONS ============
# 1.DIMENSIONS, SHAPE, AND SIZE
data.ndim
data.shape
data.size


#2. SELECTING SPECIFIC DATA

# Select all math scores (column 1)
math_scores = data[:, 1]
math_scores

# Select first 3 students' data
math_scores[:3]

# Select Math and Science scores only
math_science = data[:,[1,2]]
math_science
# ============ STATISTICAL ANALYSIS ============
# Excluding ID column (column 0)
scores = data[:, 1:]
scores
#3. MEAN, MEDIAN, STANDARD DEVIATION
np.mean(scores, axis=0)
np.median(scores, axis=0)
np.std(scores, axis=0)

#4. MIN, MAX of math scores

np.min(math_scores)
np.max(math_scores)

#5. PERCENTILES(25th,50th and 75th of Math score
np.percentile(math_scores, 25)
np.percentile(math_scores, 50)
np.percentile(math_scores, 75)
# ============ DATA MANIPULATION ============
#7. NORMALIZATION (Z-SCORE)
math_normalized = (scores - np.mean(scores)) / np.std(scores)
math_normalized
#8. SORTING DATA
# Sort by math scores (descending)
sorted_data = data[data[:, 1].argsort()[::-1]]
sorted_data

#9. FILTERING DATA

# Students with Math score > 85
data[data[:, 1] > 85]

# Students with attendance < 90%
data[data[:, 5] < 90]




#10. RESHAPING DATA

#reshape math score
reshaped_math = math_scores.reshape(5, 2)
reshaped_math



# ============ AGGREGATION ============
#11. AGGREGATIONS

#Sum of all Math scores:
np.sum(math_scores)

#Average Math score:
np.mean(math_scores)


#Total hours studied by all students:
np.sum(data[:, 4])




#12. UNIQUE VALUES AND COUNTS

# for math scores
unique_vals = np.unique(math_scores, return_counts=True)
unique_vals




#13. CUMULATIVE SUM

#Cumulative hours studied:
np.cumsum(data[:, 4])



# ============ PATTERN FINDING ============
#14. CONDITIONAL STATISTICS


# Average score of students who studied > 5 hours
avg_gt5 = np.mean(data[data[:, 4] > 5][:, 1:4], axis=0)
avg_gt5

# Average score of students who studied <= 5 hours
avg_le5 = np.mean(data[data[:, 4] <= 5][:, 1:4], axis=0)
avg_le5





#15. VARIANCE AND RANGE

#Variance of Math scores:
np.var(math_scores)

#Range of Math scores
np.ptp(math_scores)